### ISSUE TITLE
Example app doesn't build

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-webapp-example#5]
I cloned the project and ran `mvn clean package` in my terminal on Ubuntu Linux, but the build fails. Here's the full error (with extended trace).

```
$ mvn clean -e package
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building example-app 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://maven.mbed.com/com/mbed/mbed-client/3.0.0-464/mbed-client-3.0.0-464.pom
Downloading: http://maven.mbed.com/com/mbed/mbed-client-servlet/3.0.0-464/mbed-client-servlet-3.0.0-464.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.280s
[INFO] Finished at: Tue Dec 15 11:41:21 CST 2015
[INFO] Final Memory: 8M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project example-app: Could not resolve dependencies for project org.mbed.example.webapp:example-app:war:1.0-SNAPSHOT: Failed to collect dependencies for [junit:junit:jar:4.11 (test), org.assertj:assertj-core:jar:3.1.0 (test), org.slf4j:slf4j-api:jar:1.7.5 (compile), org.slf4j:slf4j-log4j12:jar:1.7.5 (compile), log4j:log4j:jar:1.2.17 (compile), log4j:apache-log4j-extras:jar:1.1 (compile), org.mockito:mockito-all:jar:1.10.19 (test), com.mbed:mbed-client:jar:3.0.0-464 (compile), com.mbed:mbed-client-servlet:jar:3.0.0-464 (compile), org.glassfish.jersey.containers:jersey-container-servlet:jar:2.18 (compile), org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.18 (compile), com.google.code.gson:gson:jar:2.3.1 (compile)]: Failed to read artifact descriptor for com.mbed:mbed-client:jar:3.0.0-464: Could not transfer artifact com.mbed:mbed-client:pom:3.0.0-464 from/to mbed repository (http://maven.mbed.com): maven.mbed.com: Name or service not known: Unknown host maven.mbed.com: Name or service not known -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project example-app: Could not resolve dependencies for project org.mbed.example.webapp:example-app:war:1.0-SNAPSHOT: Failed to collect dependencies for [junit:junit:jar:4.11 (test), org.assertj:assertj-core:jar:3.1.0 (test), org.slf4j:slf4j-api:jar:1.7.5 (compile), org.slf4j:slf4j-log4j12:jar:1.7.5 (compile), log4j:log4j:jar:1.2.17 (compile), log4j:apache-log4j-extras:jar:1.1 (compile), org.mockito:mockito-all:jar:1.10.19 (test), com.mbed:mbed-client:jar:3.0.0-464 (compile), com.mbed:mbed-client-servlet:jar:3.0.0-464 (compile), org.glassfish.jersey.containers:jersey-container-servlet:jar:2.18 (compile), org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.18 (compile), com.google.code.gson:gson:jar:2.3.1 (compile)]
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.mbed.example.webapp:example-app:war:1.0-SNAPSHOT: Failed to collect dependencies for [junit:junit:jar:4.11 (test), org.assertj:assertj-core:jar:3.1.0 (test), org.slf4j:slf4j-api:jar:1.7.5 (compile), org.slf4j:slf4j-log4j12:jar:1.7.5 (compile), log4j:log4j:jar:1.2.17 (compile), log4j:apache-log4j-extras:jar:1.1 (compile), org.mockito:mockito-all:jar:1.10.19 (test), com.mbed:mbed-client:jar:3.0.0-464 (compile), com.mbed:mbed-client-servlet:jar:3.0.0-464 (compile), org.glassfish.jersey.containers:jersey-container-servlet:jar:2.18 (compile), org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.18 (compile), com.google.code.gson:gson:jar:2.3.1 (compile)]
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:158)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
	... 22 more
Caused by: org.sonatype.aether.collection.DependencyCollectionException: Failed to collect dependencies for [junit:junit:jar:4.11 (test), org.assertj:assertj-core:jar:3.1.0 (test), org.slf4j:slf4j-api:jar:1.7.5 (compile), org.slf4j:slf4j-log4j12:jar:1.7.5 (compile), log4j:log4j:jar:1.2.17 (compile), log4j:apache-log4j-extras:jar:1.1 (compile), org.mockito:mockito-all:jar:1.10.19 (test), com.mbed:mbed-client:jar:3.0.0-464 (compile), com.mbed:mbed-client-servlet:jar:3.0.0-464 (compile), org.glassfish.jersey.containers:jersey-container-servlet:jar:2.18 (compile), org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.18 (compile), com.google.code.gson:gson:jar:2.3.1 (compile)]
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:258)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:308)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:150)
	... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.mbed:mbed-client:jar:3.0.0-464
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:296)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:186)
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCollector.java:412)
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:240)
	... 25 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.mbed:mbed-client:pom:3.0.0-464 from/to mbed repository (http://maven.mbed.com): maven.mbed.com: Name or service not known
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:281)
	... 28 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact com.mbed:mbed-client:pom:3.0.0-464 from/to mbed repository (http://maven.mbed.com): maven.mbed.com: Name or service not known
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.wagon.TransferFailedException: maven.mbed.com: Name or service not known
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:892)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
	... 4 more
Caused by: java.net.UnknownHostException: maven.mbed.com: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:922)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1316)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1269)
	at java.net.InetAddress.getAllByName(InetAddress.java:1185)
	at java.net.InetAddress.getAllByName(InetAddress.java:1119)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:278)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:162)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:746)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:886)
	... 8 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by szysas** [comment]
Sorry for that, we are having problems with our maven server. It should be back within few days.

**Comment by szysas** [comment]
Now mbed maven repository is back.
